version: '3.5'
services:
    front-end:
        container_name: front_end # Container name
        build: ./frontEnd # Location of our Dockerfile
        volumes: # Volume binding
        - './angulardockerproject:/usr/src/app' 
        ports: 
        - 4200:4200 # Port mapping
        depends_on: 
        #- Interview-service
        - user-service
        #- api-gateway
    service-registry:
        container_name: service_registry
        build: ./devServices/ServiceRegistery
        ports:
        - 8761:8761
        environment:
            eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
        depends_on: 
        - pg_database
    api-gateway:
        container_name: api-gateway
        build: ./devServices/APIGateway
        ports:
        - 8765:8765
        environment:
            eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
        depends_on: 
        - service-registry
    user-service:
        container_name: user_service
        build: ./devServices/User-Service
        ports:
        - 8770:50111
        depends_on: 
        - api-gateway
        environment:
            eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
            SPRING_DATASOURCE_URL: jdbc:postgresql://pg_database:5432/interviewDB
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: p4ssw0rd
    #Interview-service:
    #    container_name: interview_service
    #    build: ./Interview-Service/interview-service
    #    ports:
    #    - 50222:50222
    #    depends_on: 
    #    - User-service
    pg_database_user:
        container_name: pg_database_user
        image: postgres:alpine
        volumes:
        - postgres_volume:/var/lib/postgresql/interview/data
        environment:
        - POSTGRES_PASSWORD=p4ssw0rd
        - POSTGRES_USER=postgres
        - POSTGRES_DB=userDB
        ports:
        - 5432:5432
volumes: 
    postgres_volume:
